version: 0.1.{build}

image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\projects\marktext

branches:
  only:
    - master
    - develop
    - /^release-v[0-9.]+(?:-[0-9a-zA-Z\.]+)?$/
skip_tags: true

environment:
  MARKTEXT_IS_STABLE: 1
  MARKTEXT_EXIT_ON_ERROR: 1
  GH_TOKEN:
    secure: Ki5AJWygDYhzMJxl0b0rDx3bhAYmar2aPdwVHiai9IigqsvZpWHLeI3qpTiiaOWL

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 $env:PLATFORM

  - node --version
  - npm --version
  - yarn --version

  - yarn install --frozen-lockfile

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'
  - '%LOCALAPPDATA%\Yarn\cache'

build_script:
  - yarn run lint
  - yarn run validate-licenses
  - yarn run test

  - yarn run release:win

  # calculate checksums
  - ps: get-filehash -Algorithm SHA256 "build\Mark Text *.exe"
  - ps: get-filehash -Algorithm SHA256 "build\Mark Text Setup *.exe"

test: off
# test_script:
#   - yarn run test
